/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health
         * @description Reports the API's own status plus its backing services. Returns 503 when a critical dependency (PostgreSQL or Redis) is unreachable.
         */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fleet counts
         * @description Running trains counted by category, status and position source, across the whole fleet. Categories with nothing running are listed as 0, so this also says which categories `GET /trains?category=` can filter on.
         */
        get: operations["get_stats_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Running trains
         * @description Every train running now, optionally narrowed to a viewport and to categories. Each train carries its current segment, so a client can keep placing it between updates.
         */
        get: operations["list_trains_api_v1_trains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trains/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One train in detail
         * @description A trip's stops, route line and - while it runs - its position. A trip_id runs on many days: without `service_date` this is the instance running now, else the most recent to have started, else the next. Trip ids are not stable across timetable releases, so a stored id may stop resolving after a re-import.
         */
        get: operations["get_train_api_v1_trains__trip_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DatasetHealth
         * @description The timetable currently being served. Never affects ``status``.
         */
        DatasetHealth: {
            /**
             * Days Until Expiry
             * @description Negative once the feed has expired and the map has emptied.
             */
            days_until_expiry: number;
            /**
             * Feed Id
             * @example fv_free
             */
            feed_id: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /** Is Expired */
            is_expired: boolean;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date
             */
            valid_to: string;
            /**
             * Version
             * @example 20260822T084127Z-8153a8b8
             */
            version: string;
        };
        /** DependencyHealth */
        DependencyHealth: {
            /** Detail */
            detail?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Name
             * @example postgres
             */
            name: string;
            status: components["schemas"]["DependencyStatus"];
        };
        /**
         * DependencyStatus
         * @enum {string}
         */
        DependencyStatus: "ok" | "error" | "unknown";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            dataset?: components["schemas"]["DatasetHealth"] | null;
            /** Dependencies */
            dependencies: components["schemas"]["DependencyHealth"][];
            /** Environment */
            environment: string;
            status: components["schemas"]["OverallStatus"];
        };
        /**
         * OverallStatus
         * @enum {string}
         */
        OverallStatus: "ok" | "degraded";
        /**
         * PositionOut
         * @description Where a train is, as of the response's ``timestamp``.
         */
        PositionOut: {
            /**
             * Bearing
             * @description Degrees clockwise from north.
             */
            bearing: number | null;
            /**
             * Delay Seconds
             * @description `null` until realtime data arrives.
             */
            delay_seconds: number | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            position_source: components["schemas"]["PositionSource"];
            /**
             * Progress
             * @description Fraction of the segment elapsed.
             */
            progress: number;
            segment: components["schemas"]["SegmentOut"];
            status: components["schemas"]["TrainStatus"];
        };
        /**
         * PositionSource
         * @enum {string}
         */
        PositionSource: "scheduled" | "realtime";
        /**
         * RouteLineString
         * @description GeoJSON geometry, so a map can draw it as given. Coordinates are ``[lon, lat]``.
         */
        RouteLineString: {
            /** Coordinates */
            coordinates: [
                number,
                number
            ][];
            /**
             * Type
             * @default LineString
             * @constant
             */
            type: "LineString";
        };
        /**
         * SegmentOut
         * @description Everything a client needs to place the train itself at any later instant.
         */
        SegmentOut: {
            /**
             * Arrival Utc
             * Format: date-time
             */
            arrival_utc: string;
            /**
             * Departure Utc
             * Format: date-time
             */
            departure_utc: string;
            from_station: components["schemas"]["StationOut"];
            /**
             * Geometry Ref
             * @description Names a curated corridor geometry. `null` means a straight line between `from_station` and `to_station`.
             */
            geometry_ref: string | null;
            to_station: components["schemas"]["StationOut"];
        };
        /** StationOut */
        StationOut: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Name
             * @example Berlin Hbf
             */
            name: string;
            /**
             * Station Id
             * @example 256012
             */
            station_id: string;
        };
        /**
         * StatsResponse
         * @description Counts across every running train. Every key is present, zeros included.
         */
        StatsResponse: {
            /**
             * By Category
             * @description Every category in the timetable, running or not.
             * @example {
             *       "EC": 21,
             *       "ECE": 6,
             *       "EN": 0,
             *       "IC": 41,
             *       "ICE": 181,
             *       "RJ": 4
             *     }
             */
            by_category: {
                [key: string]: number;
            };
            /**
             * By Position Source
             * @example {
             *       "realtime": 0,
             *       "scheduled": 253
             *     }
             */
            by_position_source: {
                [key: string]: number;
            };
            /**
             * By Status
             * @example {
             *       "moving": 201,
             *       "stopped": 52
             *     }
             */
            by_status: {
                [key: string]: number;
            };
            /**
             * Snapshot Age Seconds
             * @description Seconds between estimating these positions and answering. 0 while positions are computed per request; once a worker writes them (Phase 6), a growing value means the worker has stopped and the data is stale.
             */
            snapshot_age_seconds: number;
            /**
             * Timestamp
             * Format: date-time
             * @description The instant the positions were estimated for.
             */
            timestamp: string;
            /**
             * Total
             * @example 253
             */
            total: number;
        };
        /** StopOut */
        StopOut: {
            /**
             * Arrival Utc
             * @description `null` at the origin.
             */
            arrival_utc: string | null;
            /**
             * Departure Utc
             * @description `null` at the terminus.
             */
            departure_utc: string | null;
            /**
             * Sequence
             * @description Position in this list, from 0 at the origin.
             */
            sequence: number;
            station: components["schemas"]["StationOut"];
        };
        /** TrainDetailResponse */
        TrainDetailResponse: {
            /** Arrival Utc */
            arrival_utc: string | null;
            /**
             * Category
             * @example ICE
             */
            category: string;
            /** Departure Utc */
            departure_utc: string | null;
            /**
             * Destination
             * @example München Hbf
             */
            destination: string;
            /**
             * Label
             * @description Line, or bare category; no train number.
             * @example ICE 10
             */
            label: string;
            /**
             * Operator
             * @example DB Fernverkehr AG
             */
            operator: string;
            origin: components["schemas"]["StationOut"];
            /** @description `null` when the trip is not running at `timestamp`. */
            position: components["schemas"]["PositionOut"] | null;
            route: components["schemas"]["RouteLineString"];
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /**
             * Snapshot Age Seconds
             * @description Seconds between estimating these positions and answering. 0 while positions are computed per request; once a worker writes them (Phase 6), a growing value means the worker has stopped and the data is stale.
             */
            snapshot_age_seconds: number;
            /** Stops */
            stops: components["schemas"]["StopOut"][];
            terminus: components["schemas"]["StationOut"];
            /**
             * Timestamp
             * Format: date-time
             * @description The instant the positions were estimated for.
             */
            timestamp: string;
            /**
             * Trip Id
             * @example 1579104
             */
            trip_id: string;
        };
        /** TrainListResponse */
        TrainListResponse: {
            /**
             * Snapshot Age Seconds
             * @description Seconds between estimating these positions and answering. 0 while positions are computed per request; once a worker writes them (Phase 6), a growing value means the worker has stopped and the data is stale.
             */
            snapshot_age_seconds: number;
            /**
             * Timestamp
             * Format: date-time
             * @description The instant the positions were estimated for.
             */
            timestamp: string;
            /** Trains */
            trains: components["schemas"]["TrainOut"][];
        };
        /**
         * TrainOut
         * @description A running train.
         */
        TrainOut: {
            /**
             * Bearing
             * @description Degrees clockwise from north.
             */
            bearing: number | null;
            /**
             * Category
             * @example ICE
             */
            category: string;
            /**
             * Delay Seconds
             * @description `null` until realtime data arrives.
             */
            delay_seconds: number | null;
            /**
             * Destination
             * @example München Hbf
             */
            destination: string;
            /**
             * Label
             * @description Line, or bare category; no train number.
             * @example ICE 10
             */
            label: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Operator
             * @example DB Fernverkehr AG
             */
            operator: string;
            position_source: components["schemas"]["PositionSource"];
            /**
             * Progress
             * @description Fraction of the segment elapsed.
             */
            progress: number;
            segment: components["schemas"]["SegmentOut"];
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            status: components["schemas"]["TrainStatus"];
            /**
             * Trip Id
             * @example 1579104
             */
            trip_id: string;
        };
        /**
         * TrainStatus
         * @enum {string}
         */
        TrainStatus: "moving" | "stopped";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_stats_api_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    list_trains_api_v1_trains_get: {
        parameters: {
            query?: {
                /** @description Viewport as `west,south,east,north` in degrees. A train is included when the bounds of its current segment overlap the box, so trains about to enter the view are already present. Must not cross the antimeridian. */
                bbox?: string | null;
                /** @description Map zoom level. Reserved for level of detail: once regional trains exist, their categories are omitted below a threshold zoom. No effect yet. */
                zoom?: number | null;
                /** @description Comma-separated categories, case-insensitive, e.g. `ICE,IC`. Unknown categories match nothing; `GET /stats` lists the ones the timetable has. */
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_train_api_v1_trains__trip_id__get: {
        parameters: {
            query?: {
                /** @description Which day's instance. */
                service_date?: string | null;
            };
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainDetailResponse"];
                };
            };
            /** @description No such trip in the timetable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
