"""Declarative base for all ORM models.

Tables arrive in Phase 2 with the GTFS import; Alembic already targets this
metadata so the first migration is an ordinary autogenerated revision.
"""

from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass
