"""phase 2 gtfs schema

Creates the static GTFS tables and their materialized daily expansion.

Two details here are worth noticing:

- ``uq_dataset_single_active`` is a **partial** unique index. It is what makes
  "at most one active dataset" a schema guarantee rather than a convention the
  application has to remember. See ADR-0002.
- ``ix_stop_point`` is declared explicitly on the model, with GeoAlchemy2's
  implicit index hook disabled, so exactly one GiST index is emitted.

Every table is keyed by ``(dataset_id, <gtfs id>)`` and cascades from
``dataset``, so pruning a superseded import is a single DELETE.

Revision ID: 736d3a81c9d5
Revises: 877b81b16c46
Create Date: 2026-08-28 14:40:18.069134

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "736d3a81c9d5"
down_revision: str | Sequence[str] | None = "877b81b16c46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('feed_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_dataset_single_active', 'dataset', ['is_active'], unique=True, postgresql_where='is_active')
    op.create_table('agency',
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('agency_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'agency_id')
    )
    op.create_table('calendar',
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('monday', sa.Boolean(), nullable=False),
    sa.Column('tuesday', sa.Boolean(), nullable=False),
    sa.Column('wednesday', sa.Boolean(), nullable=False),
    sa.Column('thursday', sa.Boolean(), nullable=False),
    sa.Column('friday', sa.Boolean(), nullable=False),
    sa.Column('saturday', sa.Boolean(), nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'service_id')
    )
    op.create_table('calendar_date',
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exception_type', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'service_id', 'date')
    )
    op.create_table('stop',
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('stop_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_station_id', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('location_type', sa.SmallInteger(), nullable=False),
    sa.Column('platform_code', sa.Text(), nullable=True),
    sa.Column('point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id', 'parent_station_id'], ['stop.dataset_id', 'stop.stop_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'stop_id')
    )
    op.create_index('ix_stop_point', 'stop', ['point'], unique=False, postgresql_using='gist')
    op.create_table('route',
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=False),
    sa.Column('agency_id', sa.String(length=64), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=False),
    sa.Column('long_name', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=8), nullable=False),
    sa.Column('line', sa.String(length=16), nullable=True),
    sa.Column('route_type', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id', 'agency_id'], ['agency.dataset_id', 'agency.agency_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'route_id')
    )
    op.create_index(op.f('ix_route_category'), 'route', ['category'], unique=False)
    op.create_table('trip',
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.String(length=64), nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id', 'route_id'], ['route.dataset_id', 'route.route_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'trip_id')
    )
    op.create_index(op.f('ix_trip_service_id'), 'trip', ['service_id'], unique=False)
    op.create_table('stop_time',
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('trip_id', sa.String(length=64), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.String(length=64), nullable=False),
    sa.Column('arrival_seconds', sa.Integer(), nullable=False),
    sa.Column('departure_seconds', sa.Integer(), nullable=False),
    sa.Column('stop_headsign', sa.Text(), nullable=True),
    sa.Column('pickup_type', sa.SmallInteger(), nullable=True),
    sa.Column('drop_off_type', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id', 'stop_id'], ['stop.dataset_id', 'stop.stop_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id', 'trip_id'], ['trip.dataset_id', 'trip.trip_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'trip_id', 'stop_sequence')
    )
    op.create_table('trip_instance',
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('trip_id', sa.String(length=64), nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=False),
    sa.Column('starts_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id', 'trip_id'], ['trip.dataset_id', 'trip.trip_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'service_date', 'trip_id')
    )
    op.create_index('ix_trip_instance_ends_at', 'trip_instance', ['dataset_id', 'ends_at_utc'], unique=False)
    op.create_index('ix_trip_instance_starts_at', 'trip_instance', ['dataset_id', 'starts_at_utc'], unique=False)
    op.create_table('stop_time_instance',
    sa.Column('dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('trip_id', sa.String(length=64), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.String(length=64), nullable=False),
    sa.Column('arrival_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departure_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id', 'service_date', 'trip_id'], ['trip_instance.dataset_id', 'trip_instance.service_date', 'trip_instance.trip_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id', 'stop_id'], ['stop.dataset_id', 'stop.stop_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'service_date', 'trip_id', 'stop_sequence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stop_time_instance')
    op.drop_index('ix_trip_instance_starts_at', table_name='trip_instance')
    op.drop_index('ix_trip_instance_ends_at', table_name='trip_instance')
    op.drop_table('trip_instance')
    op.drop_table('stop_time')
    op.drop_index(op.f('ix_trip_service_id'), table_name='trip')
    op.drop_table('trip')
    op.drop_index(op.f('ix_route_category'), table_name='route')
    op.drop_table('route')
    op.drop_index('ix_stop_point', table_name='stop', postgresql_using='gist')
    op.drop_table('stop')
    op.drop_table('calendar_date')
    op.drop_table('calendar')
    op.drop_table('agency')
    op.drop_index('uq_dataset_single_active', table_name='dataset', postgresql_where='is_active')
    op.drop_table('dataset')
    # ### end Alembic commands ###
