"""baseline

Empty starting point for the migration history. The GTFS tables arrive in
Phase 2 as autogenerated revisions on top of this one. The PostGIS extension is
created by infra/postgres/init/01-extensions.sql when the volume is first
initialised, so it is available to every migration that follows.

Revision ID: 877b81b16c46
Revises:
Create Date: 2026-08-27 16:23:58.957452

"""

from collections.abc import Sequence

revision: str = "877b81b16c46"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
